version: "3"

services:
  ates-auth:
    image: ates-auth-image
    container_name: ates-auth
    ports:
      - "5000:5000"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DB_URL: postgresql://${DB_USER}:${DB_PASSWORD}@ates-auth-db:${DB_PORT}/${DB_NAME}
    depends_on:
      - ates-kafka
      - ates-auth-db

  ates-tasks:
    image: ates-tasks-image
    container_name: ates-tasks
    ports:
      - "8000:8000"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DB_URL: postgresql://${DB_USER}:${DB_PASSWORD}@ates-auth-db:6432/${DB_NAME}
    depends_on:
      - ates-kafka
      - ates-tasks-db

  ates-auth-db:
    image: postgres:16
    container_name: ates-auth-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"

  ates-tasks-db:
    image: postgres:16
    container_name: ates-tasks-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "6432:5432"

  ates-zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: ates-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  ates-kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: ates-kafka
    ports:
      - "19092:19092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: ates-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://ates-kafka:9092,EXTERNAL://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - ates-zookeeper

  ates-kafka-ui:
    container_name: ates-kafka-ui
    image: provectuslabs/kafka-ui
    ports:
      - 8080:8080
    depends_on:
      - ates-kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_AUDIT_TOPICAUDITENABLED: true
      KAFKA_CLUSTERS_0_AUDIT_CONSOLEAUDITENABLED: true
